version: '3.8'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    networks:
      - network-reactive-spring
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb

#  app-reactive-spring:
#    image: app-reactive-spring
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    volumes:
#      - data:/app-reactive-spring
#    ports:
#      - "8090:8090"
##    environment:
#      #Overrides the host in the springboot application to use mongodb docker's hostname
##      - SPRING_DATA_MONGODB_HOST=mongodb
#    networks:
#      - network-reactive-spring
#    depends_on:
#      - mongodb


volumes:
  data: {}

networks:
  network-reactive-spring: